In [37]:
from tensorflow.keras.models import load_model
import pickle
model = load_model('model.keras')

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

with open('gender_fit_encoder.pkl', 'rb') as file:
    gender_fit_encoder = pickle.load(file)
    
with open('geography_fit_encoder.pkl', 'rb') as file:
    geography_fit_encoder = pickle.load(file)

In [38]:
input = {
    "CreditScore": 750,
    "Geography": "Germany",
    "Gender": "Male",
    "Age": 34,
    "Tenure": 5,
    "Balance": 12000.50,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 0,
    "EstimatedSalary": 85000.00
}

In [39]:
import pandas as pd
input_df = pd.DataFrame([input])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,750,Germany,Male,34,5,12000.5,2,1,0,85000.0

In [40]:
encoded_geography = geography_fit_encoder.transform([[input['Geography']]])
encoded_geography

c:\Users\Jimmy\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1 stored elements and shape (1, 3)>

In [41]:
encoded_geography_df = pd.DataFrame(encoded_geography.toarray(), columns=geography_fit_encoder.get_feature_names_out(['Geography']))
encoded_geography_df

   Geography_France  Geography_Germany  Geography_Spain
0               0.0                1.0              0.0

In [42]:
input_df = pd.concat([input_df.drop('Geography', axis=1), encoded_geography_df], axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,750,Male,34,5,12000.5,2,1,0,85000.0,0.0,1.0,0.0

In [43]:
[input['Gender']]

['Male']

In [44]:
label_gender = gender_fit_encoder.transform([input['Gender']])
input_df = pd.concat([input_df.drop('Gender', axis=1), pd.DataFrame(label_gender, columns=['Gender_Encoded'])], axis=1)

In [45]:
input_df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain,Gender_Encoded
0,750,34,5,12000.5,2,1,0,85000.0,0.0,1.0,0.0,1

In [46]:
scaled_input = scaler.transform(input_df)
scaled_input

array([[ 1.02522227, -0.46460796,  0.00666099, -1.02394714,  0.8095029 ,
         0.64259497, -1.03227043, -0.26370605, -1.01460667,  1.75486502,
        -0.57369368,  0.91601335]])

In [48]:
prediction = model.predict(scaled_input)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

array([[0.0397765]], dtype=float32)